### ISSUE TITLE
How to use YAML aliases?

### ISSUE THREAD

**Issue by agamm** [CircleCI-Public/fyaml#2]
Is it possible?

**Comment by KyleTryon** [comment]
@agamm,

Yes, this should have no effect at all on your ability to use any native YAML feature. 

Example: https://github.com/CircleCI-Public/serverless-framework-orb/blob/master/.circleci/config.yml#L16


```yaml

orb_prep_jobs: &orb_prep_jobs
  [
    orb-tools/lint,
    orb-tools/shellcheck,
    orb-tools/pack
  ]

...

- orb-tools/publish-dev:
          orb-name: circleci/serverless-framework
          context: orb-publishing
          requires: *orb_prep_jobs

```

**Comment by agamm** [comment]
@KyleTryon when I use the `circleci config pack` it outputs an error if I have an alias from a different file...

**Comment by KyleTryon** [comment]
> @KyleTryon when I use the `circleci config pack` it outputs an error if I have an alias from a different file...

Ahhh I see, I am curious, will it work if the definition is in the @orb.yml file? It may work if it is defined in the entry point.

**Comment by agamm** [comment]
> > @KyleTryon when I use the `circleci config pack` it outputs an error if I have an alias from a different file...
> 
> Ahhh I see, I am curious, will it work if the definition is in the @orb.yml file? It may work if it is defined in the entry point.

I don't quite understand, plus I don't have any orbs used atm.

**Comment by KyleTryon** [comment]
@agamm Ah, sorry, the command from the CLI is most often used to pack orbs. Could you share how you are attempting to use it exactly?

Also, it may be best to post this to the https://github.com/CircleCI-Public/circleci-cli repo. As this repo is just the spec for FYAML but the implementation should be dependant on the tool that you use that decides to implement this. To my knowledge, the CircleCI CLI may be the only tool utilizing this spec.
